# Generated by Django 3.2 on 2021-10-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, default='beat/image/default.png', null=True, upload_to='beat/image'),
        ),
    ]
