# Generated by Django 3.2 on 2021-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_orderbeat_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beats',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.OrderBeat'),
        ),
    ]
