# Generated by Django 3.2 on 1979-12-31 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_order_beats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeat',
            name='beat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.beat'),
        ),
    ]
