# Generated by Django 3.2 on 2021-10-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_order_beats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeat',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.beat'),
        ),
    ]
